### ISSUE TITLE
Trash label on Audiences should say Delete Permanently

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-analytics#142] opened 2021-03-23 14:04 UTC
When hovering over an audience on the Audiences screen, the delete button says "Trash" but this is actually a permanent action. It should say "Delete Permanently" which is inline with the list view of the Media screen.

**Comment by rmccue** [comment] 2021-04-06 09:48
Urgh yeah, this annoys me to no end, but I think it actually _does_ trash, it's just that the trash isn't viewable anywhere?

**Comment by rmccue** [comment] 2021-12-07 16:09
Duplicate of https://github.com/humanmade/aws-analytics/issues/169

**Closed by rmccue** 2021-12-07 16:09 UTC
Labels: bug
