### ISSUE TITLE
Add Cookie Consent / Opt in feature

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-analytics#9] opened 2019-05-10 15:26 UTC
No specs here fo this as it needs some research and exploration. Likely we'll look for a partnership here.

**Comment by elodiebouneau** [comment] 2020-01-30 14:14
Does this also cover GDPR acceptance?

**Comment by roborourke** [comment] 2020-01-30 16:30
It's related yeah, I was thinking to handle this in the analytics plugin but have some specific issues around privacy in there:

https://github.com/humanmade/analytics/issues?q=is%3Aissue+is%3Aopen+label%3Aprivacy

General GDPR & now CCPA compliance is perhaps better handled at this level though. We can infer whether tag manager and native analytics are being used for instance.

I think it makes sense to see what partner / 3rd party solutions we can at least document and recommend might be eg. QuantCast.

I'd also like to look at our native analytics again and see how we can remove/reduce the use of personally identifiable information to be compliant or at least not require consent by default as per the conversation with @joehoyle.

**Comment by kadamwhite** [comment] 2020-03-10 16:18
One interesting requirement from one of our Altis clients is that they want to have the cookie notice at bottom, but to be able to add first-party notices above that, which can each be dismissed separately (and for which dismissal is persisted separately). This won't be a common requirement but a provider that supported this feature would be :100:

**Comment by PriyaBhatia0210** [comment] 2020-03-23 21:11
Adding references to the requirement mentioned above by @kadamwhite : 
![image](https://user-images.githubusercontent.com/55112796/77363434-1dd7f380-6d29-11ea-957c-abf44ad6bbb6.png)
![image (1)](https://user-images.githubusercontent.com/55112796/77363447-22041100-6d29-11ea-949e-1124eae7182e.png)

**Comment by jennybeaumont** [comment] 2020-10-07 14:59
Closing as duplicate of https://github.com/humanmade/platform-dev/issues/545

**Closed by jennybeaumont** 2020-10-07 14:59 UTC
Labels: enhancement, help wanted, question
