### ISSUE TITLE
Audience Estimation Doesn't Add Up

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-analytics#90] opened 2020-11-23 10:28 UTC
Steps to reproduce:
1. Create an audience based off country "GB", observe estimate (say 18%)
1. Change the "compare" to "is not"
1. I'd expect the number to flip to 82%, however it doesn't, is 70%/

![Screenshot 2020-11-23 at 11 28 12 AM](https://user-images.githubusercontent.com/161683/99951856-043af000-2d7f-11eb-9319-53601f594c05.png)
![Screenshot 2020-11-23 at 11 28 18 AM](https://user-images.githubusercontent.com/161683/99951858-04d38680-2d7f-11eb-8c2b-aad5ca42ddc6.png)

Acceptance criteria:

Above is shown at https://www.altis-dxp.com/wp-admin/admin.php?page=audience

**Comment by roborourke** [comment] 2020-11-24 11:41
Yeah those numbers are low enough that the cardinality aggregation should be accurate... mysterious.

**Comment by shadyvb** [comment] 2021-08-18 15:24
This seems to be working as expected now, check the % in the select box and the % of the audience preview on the right, tried different combos and still couldn't reproduce.
![image.png](https://images.zenhubusercontent.com/570267946caf56c9d38f3a03/b074d902-b7c0-48be-a79a-7d80f51af7ac)

**Comment by roborourke** [comment] 2021-08-18 17:29
Ah might’ve jumped the gun here, it’s the percentages for things like os is Mac vs is not Mac for example

**Comment by shadyvb** [comment] 2021-08-19 06:53
Yeah, I doesn't happen with the browser metric but happens with OS, interesting ... 🤔

**Comment by shadyvb** [comment] 2021-08-19 07:43
I thought this might be related to audience estimations not factoring empty values in `not in` queries, so I flushed the cache to try it out, which seems to work, but not because I altered the query in a debug session, because I flushed the cache. The audience total size changed from 898 to 822 after flushing the cache, so it seems like this is caused by stale cache of the total entries count vs the fresh queried filtered audience count.

I'll try to synchronise both caches to align the timing and make this a bit more accurate.

**Comment by roborourke** [comment] 2021-08-19 13:21
Fixed by https://github.com/humanmade/aws-analytics/pull/251

**Closed by roborourke** 2021-08-19 13:21 UTC
Labels: bug, should have
