### ISSUE TITLE
Navigating away from Audience Add / Edit doesn't cause warning

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-analytics#96] opened 2020-11-25 09:57 UTC
Steps to reproduce:
1. Be Noel
1. Edit an audience
1. Make some changes
1. Navigate away from the page
1. Lose all modifications made to audience, thinking it has all updated and been saved

Acceptance criteria:

- [x] I see a "page unload" popup warning telling me I have not saved my audience.

**Comment by roborourke** [comment] 2021-01-27 16:30
Unable to reproduce step 1, closing as wontfix 😛

**Closed** 2021-01-29 10:19 UTC
Labels: bug, must have
