### ISSUE TITLE
Add a validation check to add new CTA when moving from one conversion goal type to another  

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-analytics#109] opened 2021-01-15 17:30 UTC
![image](https://user-images.githubusercontent.com/55112796/104652677-7ba64500-5687-11eb-962d-d2b775a7fdb3.png)

We'd likely need to prioritise adding validation checks for what sort of inputs are acceptable.

Eg: in this case, I first added the conversion goal as 'click on any link'. That worked well showing me as one conversion thats seen above. However, when I go back to the editor and select a different conversion goal i.e. submit a form, and update the page, I do not get an error message to say that I have not actually added a form to see the conversion. And when I go back to the editor again, it still continues to show the one conversion from the previous conversion goal.

**Comment by roborourke** [comment] 2021-01-19 11:03
This is a duplicate of #82 as it'd work via the same mechanism, any validation check would be run when the conversion goal is changed. It could be added as an acceptance criteria to the original issue.

**Comment by roborourke** [comment] 2021-01-20 18:32
Going to close this out in favour of the original issue. If you still feel like it's significantly different you can reopen it but at least from my technical perspective it's already captured.

**Closed by roborourke** 2021-01-20 18:32 UTC
Labels: duplicate, enhancement, must have

**Comment by PriyaBhatia0210** [comment] 2021-01-20 22:27
Hey @roborourke , yeah I wanted to go back and close #82 actually and refine this one further. But I have refined #82 now to include the details I wanted to. Added the above as a use case in comments. 
You are right the issues are essentially the same. Just wanted to start a new issue while testing and get to writing the correct details before I closed. Thanks.
